export const mockData = [
  {
    id: 1,
    date: "24-11-2020",
    name: "Item1",
    type: "VPC Flow Logs",
    size: 32,
    state: "active",
  },
  {
    id: 2,
    date: "24-11-2020",
    name: "Item2",
    type: "VPC Flow Logs",
    size: 24,
    state: "active",
  },
  {
    id: 3,
    date: "24-11-2020",
    name: "Item3",
    type: "VPC Flow Logs",
    size: 67,
    state: "active",
  },
  {
    id: 4,
    date: "24-11-2020",
    name: "Item4",
    type: "VPC Flow Logs",
    size: 6,
    state: "available",
  },
  {
    id: 5,
    date: "29-11-2020",
    name: "Item5",
    type: "VPC Flow Logs",
    size: 12,
    state: "restoring",
  },
  {
    id: 6,
    date: "30-11-2020",
    name: "Item1",
    type: "VPC Flow Logs",
    size: 32,
    state: "active",
  },
  {
    id: 13,
    date: "30-11-2020",
    name: "Item3",
    type: "VPC Flow Logs",
    size: 67,
    state: "active",
  },
  {
    id: 17,
    date: "30-11-2020",
    name: "Item5",
    type: "NLB Logs",
    size: 400,
    state: "active",
  },
];
