export const mockData = [
  {
    id: 1,
    date: new Date("2020-03-25"),
    indexName: "Item1",
    indexSize: 32,
    indexState: "active",
  },
  {
    id: 2,
    date: new Date("2020-04-15"),
    indexName: "Item2",
    indexSize: 24,
    indexState: "active",
  },
  {
    id: 3,
    date: new Date("2020-04-15"),
    indexName: "Item3",
    indexSize: 67,
    indexState: "active",
  },
  {
    id: 4,
    date: new Date(),
    indexName: "Item4",
    indexSize: 6,
    indexState: "active",
  },
  {
    id: 5,
    date: new Date(),
    indexName: "Item5",
    indexSize: 12,
    indexState: "active",
  },
  {
    id: 6,
    date: new Date("2020-03-25"),
    indexName: "Item1",
    indexSize: 32,
    indexState: "active",
  },
  {
    id: 7,
    date: new Date("2020-04-15"),
    indexName: "Item2",
    indexSize: 24,
    indexState: "active",
  },
  {
    id: 8,
    date: new Date("2020-04-15"),
    indexName: "Item3",
    indexSize: 67,
    indexState: "active",
  },
  {
    id: 9,
    date: new Date(),
    indexName: "Item4",
    indexSize: 6,
    indexState: "active",
  },
  {
    id: 10,
    date: new Date(),
    indexName: "Item5",
    indexSize: 12,
    indexState: "active",
  },
  {
    id: 11,
    date: new Date("2020-03-25"),
    indexName: "Item1",
    indexSize: 32,
    indexState: "active",
  },
  {
    id: 12,
    date: new Date("2020-04-15"),
    indexName: "Item2",
    indexSize: 24,
    indexState: "active",
  },
  {
    id: 13,
    date: new Date("2020-04-15"),
    indexName: "Item3",
    indexSize: 67,
    indexState: "active",
  },
  {
    id: 14,
    date: new Date(),
    indexName: "Item4",
    indexSize: 6,
    indexState: "active",
  },
  {
    id: 15,
    date: new Date(),
    indexName: "Item5",
    indexSize: 12,
    indexState: "active",
  },
];
